#!/usr/bin/env node

var path = require('path');
var cp = require('child_process');

const TARGET = '0.26.0';

process.chdir(path.dirname(__dirname));
var child = cp.exec('npm install --msvs_version=2013', 
                    {
                        npm_config_disturl: 'https://atom.io/download/electron',
                        npm_config_target: TARGET,
                        npm_config_arch: process.arch
                    },
                    function(error, stdout, stderr) {
                        if (error) {
                            process.exit(error.code || 1);
                        }
                    });
child.stderr.pipe(process.stderr);
child.stdout.pipe(process.stdout);